# Generated by Django 5.0.1 on 2024-02-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_options_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
